basePath: /
definitions:
  Response.ResponseStructure:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: localhost:8090
info:
  contact:
    email: example@some.com
    name: www.topgoer.com
    url: https://www.topgoer.com
  description: This is a  server of IndustrialInternet.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.topgoer.com
  title: IndustrialInternet项目API
  version: "1.0"
paths:
  /api/login:
    get:
      description: 普通GET测试接口描述信息
      responses:
        "200":
          description: code":200,"data":null,"msg":""}
          schema:
            $ref: '#/definitions/Response.ResponseStructure'
      summary: 普通GET测试
      tags:
      - Test
  /api/msgOK:
    get:
      description: NormalOKTest测试接口描述信息
      responses:
        "200":
          description: code":200,"data":null,"msg":""}
          schema:
            $ref: '#/definitions/Response.ResponseStructure'
      summary: NormalOKTest测试接口
      tags:
      - Test
  /api/normal:
    get:
      description: NormalTest测试接口描述信息
      responses:
        "200":
          description: code":200,"data":null,"msg":""}
          schema:
            $ref: '#/definitions/Response.ResponseStructure'
      summary: NormalTest测试接口
      tags:
      - Test
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: 登录测试接口描述信息
      parameters:
      - description: 用户名
        in: path
        name: username
        required: true
        type: string
      - description: 密码
        in: path
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":200,"msg":"","data":null}
          schema:
            $ref: '#/definitions/Response.ResponseStructure'
      summary: 登录测试接口
      tags:
      - 登录
  /api/v1/notfound:
    get:
      description: notfound测试接口描述信息
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: notfound测试接口
      tags:
      - NotFound
swagger: "2.0"
